module.exports = {
	"MBBANK":"Military",
    "MB BANK ":"Military",
    "MB BANK":"Military",
	"NGAN HANG A CHAU":"ACB",
	"WOORI BANK":"WOORI BANK",
	"NH LD VIET NGA":"Vietnam - Russia",
	"VPBANK CAKE":"Cake Digital Bank",
	"VPBANK":"VPBANK Vietnam",
	"VP DIRECT":"VPBANK Vietnam",
	"VIETNAM DEVELOPMENT BANK":"Vietnam Development",
	"VIETINBANK":"Industry And Trade",
	"VIETCOMBANK":"Foreign Trade of Vietnam",
	"NHTMCP BAN VIET":"Vietcapital Commercial",
	"VIETBANK":"Vietnam Thuong Tin",
	"VIETA BANK":"Viet A Commercial",
	"VIB BANK":"Vietnam International",
	"VBSP":"Social Policies",
	"UNITED OVERSEAS BANK":"United Overseas",
	"U BANK":"Ubank Digital Bank",
	"TIENPHONG BANK":"Tien Phong Commercial",
	"SHINHAN BANK VN":"Shinhan Bank",
	"SHB BANK":"Saigon Hanoi Commercial",
	"SEABANK":"Southeast Asia Commercial",
	"SCB":"SCB Sai Gon Joint Stock",
	"SAIGONBANK":"SAIGONBANK Sai Gon Joint Stock",
	"SACOMBANK":"Sacombank",
	"PVCOMBANK":"Vietnam Public",
	"PG bank":"Petrolimex Group",
	"PBVN":"",
	"Orient Commercial Bank,OCB":"Orient Commercial",
	"OCEANBANK":"Ocean Commercial",
	"NongHyup Bank Hanoi Branch":"Nonghyup Bank",
	"NH TMCP QUOC DAN":"National Citizen",
	"NAMA BANK":"Nam A Comercial",
	"MARITIME BANK":"Vietnam Maritime",
	"LIENVIET BANK":"LienViet Post",
	"KIENLONGBANK":"Kien Long",
	"Kbank":"KASIKORNBANK",
	"INDOVINA BANK":"Indovina Bank",
	"IBK":"Korea - Ho Chi Minh",
	"HSBC":"HSBC Bank",
	"HONGLEONG BANK":"Hong Leong",
	"HD BANK":"Ho Chi Minh City Development",
	"GP BANK":"Global Petro",
	"EXIMBANK":"Export Import Bank",
	"DONGA BANK":"Dong A Commercial",
	"DBS":"Singapore Limited",
	"Co-opBank":"Co-Operative",
	"NH MTV CIMB":"CIMB Bank",
	"NH TM TNHH MTV XAY DUNG VIET NAM":"Vietnam Construction",
	"BIDV BANK":"Development of Vietnam JSC",
	"BAO VIET BANK":"Bao Viet Joint",
	"BAC A BANK":"Bac A Commercial",
	"AGRIBANK":"Agriculture and Rural",
	"ABBANK":"An Binh Commercial",
	"Techcom Bank":"Techcom",
	"PGBANK":"PG"
}